# Plauderkiste Konfiguration für User 1

# Eindeutiger Nutzername (Handle)
handle = "Hulk"

# TCP-Port für eingehende Nachrichten/Bilder (muss pro User unterschiedlich sein)
port = 5001

# UDP-Port für Discovery (alle Peers müssen denselben UDP-Port verwenden)
whoisport = 4000

# Ordner für empfangene Bilder
imagepath = "./images1"
